@startwbs
+ Utilisateur connecté avec le rôle lecteur
++ Page Accueil
+++ Page d'une catégorie
+++ Page d'un article
++ Blog
+++ Page d'une catégorie
+++ Page d'un article
++ Contact
++ Page de profil
+++ Page modifications veilles favorites
+++ Page modifications alertes mail
+++ Page modifications informations personnelles
+++ Page modifications mot de passe
@endwbs
